# Generated by Django 5.2.7 on 2025-11-07 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models




def create_default_category(apps, schema_editor):
    # Migratsiya vaqtida modelning holatini oling
    Category = apps.get_model('posts', 'Category')
    Post = apps.get_model('posts', 'Post')

    # 1. Default kategoriyani yaratish
    default_category = Category.objects.create(name='Boshqa')

    # 2. Mavjud barcha postlarning category_id maydonini yangi ID ga o'rnatish
    # Shu orqali IntegrityError xatosi oldi olinadi
    Post.objects.filter(category__isnull=True).update(category=default_category)

    # Agar sizning avvalgi Postlaringizda umuman category maydoni bo'lmagan bo'lsa,
    # u holda barcha Postlarni yangilang:
    # Post.objects.all().update(category=default_category)

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='kategoriya')),
            ],
        ),
        # migrations.RunPython(create_default_category),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='avtor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='mazmuni'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="jaratilg'an waqti"),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='atamasi'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.category', verbose_name='Kategoriya'),
            preserve_default=False,
        ),
    ]
